module.exports = function() {
    return [

    // SELF OPT IN
    {
        'request': {
            'method': 'POST',
            'headers': {
                'Authorization': ['Basic ' + new Buffer('test:test').toString('base64')],
                'Content-Type': ['multipart/formdata; boundary=yolo']
            },
            'url': 'http://test/v2/',
            'body': [
                '--yolo',
                'Content-Disposition: form-data; name="ihe-mhd-metadata"; filename="MHDMetadata.json"',
                'Content-Type: application/json',
                '',
                '{"documentEntry":{"patientId":"5101015009088^^^ZAF^NI","uniqueId":"2.25.169380846032024","entryUUID":"urn:uuid:b18c62b4-828e-4b52-25c9-725a1f43fb37","classCode":{"code":"51855-5","codingScheme":"2.16.840.1.113883.6.1","codeName":"Patient Note"},"typeCode":{"code":"51855-5","codingScheme":"2.16.840.1.113883.6.1","codeName":"Patient Note"},"formatCode":{"code":"npr-pn-cda","codingScheme":"4308822c-d4de-49db-9bb8-275394ee971d","codeName":"NPR Patient Note CDA"},"mimeType":"text/xml","hash":"3d8840c83cb6831cb6b3cfbf3f2e0215393a2885","size":5350}}',
                '',
                '--yolo',
                'Content-Disposition: form-data; name="content"; filename="CDARequest.xml"',
                'Content-Type: text/xml',
                '',
                '<?xml version="1.0" encoding="UTF-8"?>',
                '<ClinicalDocument xmlns="urn:hl7-org:v3" xmlns:cda="urn:hl7-org:v3" xmlns:voc="urn:hl7-org:v3/voc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:pcc="urn:ihe:pcc:hl7v3" xmlns:lab="urn:oid:1.3.6.1.4.1.19376.1.3.2" xmlns:sdtc="urn:hl7-org:sdtc" xsi:schemaLocation="urn:hl7-org:v3 CDA.xsd">',
                '<typeId root="2.16.840.1.113883.1.3" extension="POCD_HD000040"/>',
                '<templateId root="2.16.840.1.113883.10" extension="IMPL_CDAR2_LEVEL1"/>',
                '<id root="b18c62b4-828e-4b52-25c9-725a1f43fb37"/>',
                '<code code="51855-5" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC"/>',
                '<title>SA National Pregnancy Register - Patient Note</title>',
                '<!-- Creation time of document, e.g. 20140217121212 -->',
                '<effectiveTime value="20130819144811"/>',
                '<confidentialityCode code="N" displayName="Normal" codeSystem="2.16.840.1.113883.5.25" codeSystemName="Confidentiality"/>',
                '<languageCode code="en-UK"/>',
                '<!-- Client details -->',
                '<recordTarget>',
                '  <patientRole>',
                '    <!-- Patient Identifier -->',
                '    <!-- The value for extension must be specified in HL7 CX format: -->',
                '    <!-- id^^^assigningAuthority^typeCode -->',
                '    <!-- The typeCode specified the type of identifier, e.g. NI for National Identifier or PPN for Passport Number -->',
                '    <!-- The assigningAuthority specifies the issuer of the id, e.g. ZAR for South Africa -->',
                '    <!-- An example for a South African National ID is: -->',
                '    <!-- <id extension="7612241234567^^^ZAF^NI" root="526ef9c3-6f18-420a-bc53-9b733920bc67" /> -->',
                '    <id extension="5101015009088^^^ZAF^NI" root="526ef9c3-6f18-420a-bc53-9b733920bc67"/>',
                '    <addr/>',
                '    <!-- Telephone number in RFC3966 format, e.g. tel:+27731234567 -->',
                '    <telecom value="tel:+27002"/>',
                '    <patient>',
                '      <name>',
                '        ',
                '        ',
                '      <given nullFlavor="NI"/><family nullFlavor="NI"/></name>',
                '      <administrativeGenderCode code="F" codeSystem="2.16.840.1.113883.5.1"/>',
                '      <!-- e.g. 19700123 -->',
                '      <birthTime value="19510101"/>',
                '      <languageCommunication>',
                '        <languageCode code="en"/>',
                '        <preferenceInd value="true"/>',
                '      </languageCommunication>',
                '    </patient>',
                '  </patientRole>',
                '</recordTarget>',
                '<!-- HCW Details -->',
                '<author>',
                '  <time value="20130819144811"/>',
                '  <assignedAuthor>',
                ' ',
                ' <addr/>',
                ' ',
                ' <assignedPerson>',
                '   <name>',
                '   ',
                '   ',
                '   <given nullFlavor="NI"/><family nullFlavor="NI"/></name>',
                ' </assignedPerson>',
                ' <representedOrganization>',
                '   ',
                '   ',
                ' <id nullFlavor="NI"/><name nullFlavor="NI"/></representedOrganization>',
                '  <telecom nullFlavor="NI"/><id nullFlavor="NI"/></assignedAuthor>',
                '</author>',
                '<custodian>',
                '  <assignedCustodian>',
                ' <representedCustodianOrganization>',
                '   <id root="a5881e6c-b42e-4559-a1fd-d1dc52379658"/>',
                '   <name>SA National Department of Health</name>',
                ' </representedCustodianOrganization>',
                '  </assignedCustodian>',
                '</custodian>',
                '<documentationOf>',
                '  <serviceEvent classCode="PCPR">',
                ' <effectiveTime value="20130819"/>',
                '  </serviceEvent>',
                '</documentationOf>',
                '<component>',
                '  <structuredBody>',
                ' <component>',
                '   <section>',
                '   <code code="57060-6" displayName="Estimated date of delivery Narrative" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC"/>',
                '   <text>',
                '     <table>',
                '     <thead>',
                '       <tr>',
                '       <td>Pregnancy status</td>',
                '       <td>Note Date</td>',
                '       <td>Delivery Date (Estimated)</td>',
                '       </tr>',
                '     </thead>',
                '     <tbody>',
                '       <!-- e.g. -->',
                '       <tr>',
                '       <td>Pregnancy confirmed</td>',
                '       <td>2014-02-17</td>',
                '       <td>2014-10-17</td>',
                '       </tr>',
                '     </tbody>',
                '     </table>',
                '   </text>',
                '   <entry>',
                '     <!-- Pregnancy Status -->',
                '     <observation classCode="OBS" moodCode="EVN">',
                '     <code code="11449-6" displayName="Pregnancy status" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC"/>',
                '     <text/>',
                '     <statusCode code="completed"/>',
                '     <!-- e.g. 20140217 -->',
                '     <effectiveTime value="20130819"/>',
                '     <!-- one of \'value\' -->',
                '     <value xsi:type="CE" code="77386006" displayName="Pregnancy confirmed" codeSystem="2.16.840.1.113883.6.96" codeSystemName="SNOMED CT"/>',
                '     <!--<value xsi:type="CE" code="102874004" displayName="Unconfirmed pregnancy" codeSystem="2.16.840.1.113883.6.96" codeSystemName="SNOMED CT"/>-->',
                '     <!--<value xsi:type="CE" code="60001007" displayName="Not pregnant" codeSystem="2.16.840.1.113883.6.96" codeSystemName="SNOMED CT"/>-->',
                '     <!--<value xsi:type="CE" code="289256000" displayName="Mother delivered" codeSystem="2.16.840.1.113883.6.96" codeSystemName="SNOMED CT"/>-->',
                '     <!-- Remove entryRelationship if \'Not pregnant\' -->',
                '     <entryRelationship typeCode="SPRT" inversionInd="true">',
                '       <!-- Delivery Date -->',
                '       <observation classCode="OBS" moodCode="EVN">',
                '       <!-- one of \'code\' -->',
                '       <code code="11778-8" displayName="Delivery date Estimated" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC"/>',
                '       <!-- <code code="8665-2" displayName="Last menstrual period start date" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC"/> -->',
                '       <!-- Delivery Date (if \'Mother Delivered\') -->',
                '       <!-- <code code="21112-8" displayName="Birth date" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC"/> -->',
                '       <text/>',
                '       <statusCode code="completed"/>',
                '       <!-- e.g. 20141017 -->',
                '       <value xsi:type="TS" value="20130819"/>',
                '       </observation>',
                '     </entryRelationship>',
                '     </observation>',
                '   </entry>',
                '   </section>',
                ' </component>',
                '  </structuredBody>',
                '</component>',
                '</ClinicalDocument>'
            ].join('\n')
        },
        'response': {
            'body': ''
        }
    },
    // // SELF OPT IN 2
    // {
    //     'request': {
    //         'method': 'POST',
    //         'headers': {
    //             'Authorization': ['Basic ' + new Buffer('test:test').toString('base64')],
    //             'Content-Type': ['multipart/formdata; boundary=yolo']
    //         },
    //         'url': 'http://test/v2/',
    //         'body': [
    //             '--yolo',
    //             'Content-Disposition: form-data; name="ihe-mhd-metadata"; filename="MHDMetadata.json"',
    //             'Content-Type: application/json',
    //             '',
    //             '{"documentEntry":{"patientId":"2012315678097^^^ZAF^NI","uniqueId":"2.25.169380846032024","entryUUID":"urn:uuid:b18c62b4-828e-4b52-25c9-725a1f43fb37","classCode":{"code":"51855-5","codingScheme":"2.16.840.1.113883.6.1","codeName":"Patient Note"},"typeCode":{"code":"51855-5","codingScheme":"2.16.840.1.113883.6.1","codeName":"Patient Note"},"formatCode":{"code":"npr-pn-cda","codingScheme":"4308822c-d4de-49db-9bb8-275394ee971d","codeName":"NPR Patient Note CDA"},"mimeType":"text/xml","hash":"9d4b6b60665c560d836b2e48a9cec8398e2ee68f","size":5350}}',
    //             '',
    //             '--yolo',
    //             'Content-Disposition: form-data; name="content"; filename="CDARequest.xml"',
    //             'Content-Type: text/xml',
    //             '',
    //             '<?xml version="1.0" encoding="UTF-8"?>',
    //             '<ClinicalDocument xmlns="urn:hl7-org:v3" xmlns:cda="urn:hl7-org:v3" xmlns:voc="urn:hl7-org:v3/voc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:pcc="urn:ihe:pcc:hl7v3" xmlns:lab="urn:oid:1.3.6.1.4.1.19376.1.3.2" xmlns:sdtc="urn:hl7-org:sdtc" xsi:schemaLocation="urn:hl7-org:v3 CDA.xsd">',
    //             '<typeId root="2.16.840.1.113883.1.3" extension="POCD_HD000040"/>',
    //             '<templateId root="2.16.840.1.113883.10" extension="IMPL_CDAR2_LEVEL1"/>',
    //             '<id root="b18c62b4-828e-4b52-25c9-725a1f43fb37"/>',
    //             '<code code="51855-5" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC"/>',
    //             '<title>SA National Pregnancy Register - Patient Note</title>',
    //             '<!-- Creation time of document, e.g. 20140217121212 -->',
    //             '<effectiveTime value="20130819144811"/>',
    //             '<confidentialityCode code="N" displayName="Normal" codeSystem="2.16.840.1.113883.5.25" codeSystemName="Confidentiality"/>',
    //             '<languageCode code="en-UK"/>',
    //             '<!-- Client details -->',
    //             '<recordTarget>',
    //             '  <patientRole>',
    //             '    <!-- Patient Identifier -->',
    //             '    <!-- The value for extension must be specified in HL7 CX format: -->',
    //             '    <!-- id^^^assigningAuthority^typeCode -->',
    //             '    <!-- The typeCode specified the type of identifier, e.g. NI for National Identifier or PPN for Passport Number -->',
    //             '    <!-- The assigningAuthority specifies the issuer of the id, e.g. ZAR for South Africa -->',
    //             '    <!-- An example for a South African National ID is: -->',
    //             '    <!-- <id extension="7612241234567^^^ZAF^NI" root="526ef9c3-6f18-420a-bc53-9b733920bc67" /> -->',
    //             '    <id extension="2012315678097^^^ZAF^NI" root="526ef9c3-6f18-420a-bc53-9b733920bc67"/>',
    //             '    <addr/>',
    //             '    <!-- Telephone number in RFC3966 format, e.g. tel:+27731234567 -->',
    //             '    <telecom value="tel:+27002"/>',
    //             '    <patient>',
    //             '      <name>',
    //             '        ',
    //             '        ',
    //             '      <given nullFlavor="NI"/><family nullFlavor="NI"/></name>',
    //             '      <administrativeGenderCode code="F" codeSystem="2.16.840.1.113883.5.1"/>',
    //             '      <!-- e.g. 19700123 -->',
    //             '      <birthTime value="19510101"/>',
    //             '      <languageCommunication>',
    //             '        <languageCode code="en"/>',
    //             '        <preferenceInd value="true"/>',
    //             '      </languageCommunication>',
    //             '    </patient>',
    //             '  </patientRole>',
    //             '</recordTarget>',
    //             '<!-- HCW Details -->',
    //             '<author>',
    //             '  <time value="20130819144811"/>',
    //             '  <assignedAuthor>',
    //             ' ',
    //             ' <addr/>',
    //             ' ',
    //             ' <assignedPerson>',
    //             '   <name>',
    //             '   ',
    //             '   ',
    //             '   <given nullFlavor="NI"/><family nullFlavor="NI"/></name>',
    //             ' </assignedPerson>',
    //             ' <representedOrganization>',
    //             '   ',
    //             '   ',
    //             ' <id nullFlavor="NI"/><name nullFlavor="NI"/></representedOrganization>',
    //             '  <telecom nullFlavor="NI"/><id nullFlavor="NI"/></assignedAuthor>',
    //             '</author>',
    //             '<custodian>',
    //             '  <assignedCustodian>',
    //             ' <representedCustodianOrganization>',
    //             '   <id root="a5881e6c-b42e-4559-a1fd-d1dc52379658"/>',
    //             '   <name>SA National Department of Health</name>',
    //             ' </representedCustodianOrganization>',
    //             '  </assignedCustodian>',
    //             '</custodian>',
    //             '<documentationOf>',
    //             '  <serviceEvent classCode="PCPR">',
    //             ' <effectiveTime value="20130819"/>',
    //             '  </serviceEvent>',
    //             '</documentationOf>',
    //             '<component>',
    //             '  <structuredBody>',
    //             ' <component>',
    //             '   <section>',
    //             '   <code code="57060-6" displayName="Estimated date of delivery Narrative" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC"/>',
    //             '   <text>',
    //             '     <table>',
    //             '     <thead>',
    //             '       <tr>',
    //             '       <td>Pregnancy status</td>',
    //             '       <td>Note Date</td>',
    //             '       <td>Delivery Date (Estimated)</td>',
    //             '       </tr>',
    //             '     </thead>',
    //             '     <tbody>',
    //             '       <!-- e.g. -->',
    //             '       <tr>',
    //             '       <td>Pregnancy confirmed</td>',
    //             '       <td>2014-02-17</td>',
    //             '       <td>2014-10-17</td>',
    //             '       </tr>',
    //             '     </tbody>',
    //             '     </table>',
    //             '   </text>',
    //             '   <entry>',
    //             '     <!-- Pregnancy Status -->',
    //             '     <observation classCode="OBS" moodCode="EVN">',
    //             '     <code code="11449-6" displayName="Pregnancy status" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC"/>',
    //             '     <text/>',
    //             '     <statusCode code="completed"/>',
    //             '     <!-- e.g. 20140217 -->',
    //             '     <effectiveTime value="20130819"/>',
    //             '     <!-- one of \'value\' -->',
    //             '     <value xsi:type="CE" code="77386006" displayName="Pregnancy confirmed" codeSystem="2.16.840.1.113883.6.96" codeSystemName="SNOMED CT"/>',
    //             '     <!--<value xsi:type="CE" code="102874004" displayName="Unconfirmed pregnancy" codeSystem="2.16.840.1.113883.6.96" codeSystemName="SNOMED CT"/>-->',
    //             '     <!--<value xsi:type="CE" code="60001007" displayName="Not pregnant" codeSystem="2.16.840.1.113883.6.96" codeSystemName="SNOMED CT"/>-->',
    //             '     <!--<value xsi:type="CE" code="289256000" displayName="Mother delivered" codeSystem="2.16.840.1.113883.6.96" codeSystemName="SNOMED CT"/>-->',
    //             '     <!-- Remove entryRelationship if \'Not pregnant\' -->',
    //             '     <entryRelationship typeCode="SPRT" inversionInd="true">',
    //             '       <!-- Delivery Date -->',
    //             '       <observation classCode="OBS" moodCode="EVN">',
    //             '       <!-- one of \'code\' -->',
    //             '       <code code="11778-8" displayName="Delivery date Estimated" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC"/>',
    //             '       <!-- <code code="8665-2" displayName="Last menstrual period start date" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC"/> -->',
    //             '       <!-- Delivery Date (if \'Mother Delivered\') -->',
    //             '       <!-- <code code="21112-8" displayName="Birth date" codeSystem="2.16.840.1.113883.6.1" codeSystemName="LOINC"/> -->',
    //             '       <text/>',
    //             '       <statusCode code="completed"/>',
    //             '       <!-- e.g. 20141017 -->',
    //             '       <value xsi:type="TS" value="20130819"/>',
    //             '       </observation>',
    //             '     </entryRelationship>',
    //             '     </observation>',
    //             '   </entry>',
    //             '   </section>',
    //             ' </component>',
    //             '  </structuredBody>',
    //             '</component>',
    //             '</ClinicalDocument>'
    //         ].join('\n')
    //     },
    //     'response': {
    //         'body': ''
    //     }
    // },
    ];
};
